Dose.destroy_all
Ingredient.destroy_all

Ingredient.create!(name: "Lemon")
Ingredient.create!(name: "Bacon")
Ingredient.create!(name: "Strawberry")
Ingredient.create!(name: "Orange")
Ingredient.create!(name: "Ginger Ale")
Ingredient.create!(name: "Ginger")
Ingredient.create!(name: "Grape")
Ingredient.create!(name: "Basil")
Ingredient.create!(name: "Rosemary")
Ingredient.create!(name: "Pineapple")
Ingredient.create!(name: "Coconut milk")
Ingredient.create!(name: "Egg white")
Ingredient.create!(name: "Blueberry")
Ingredient.create!(name: "Blackberry")
Ingredient.create!(name: "Raspberry")
Ingredient.create!(name: "Cherry")
Ingredient.create!(name: "Cherry tomato")
Ingredient.create!(name: "Mint leaves")
Ingredient.create!(name: "Lime")
Ingredient.create!(name: "Lichia")
Ingredient.create!(name: "Ground black pepper ")
Ingredient.create!(name: "Salt")
Ingredient.create!(name: "Sugar")
Ingredient.create!(name: "Ice")
Ingredient.create!(name: "Dry vermouth")
Ingredient.create!(name: "Angostura")
Ingredient.create!(name: "Gin")
Ingredient.create!(name: "Vodka")
Ingredient.create!(name: "Whisky")
Ingredient.create!(name: "Tomato jouice")
Ingredient.create!(name: "Lemon juice")
Ingredient.create!(name: "Cachaca")
Ingredient.create!(name: "Prosecco")
Ingredient.create!(name: "Aperol")
Ingredient.create!(name: "Soda water")
Ingredient.create!(name: "Bourbon")
Ingredient.create!(name: "Sake")
